### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by Andrxia** [AeiouEnigma/sodium-forge#11]
### Reproduction Steps

1. Flying around the world in creative. 

### Crash Report File
https://gist.github.com/Andrxia/2ee87fe52c75ac9ebcd204bd815f31cf

### Additional Information
I can't figure out what is causing this.. all it shows is smth about sodium. Also new to GitHub so apologies if my report isnt very clear. When I walk around slowly around the world nothing crashes, but when I fly to explore more chunks it crashes. I've tried multiple worlds but this still continues to happen.

**Comment by hf29h8sh321** [comment]
Please reopen, I'm getting the same issue.
